### ISSUE TITLE
프로젝트 리팩토링

### ISSUE THREAD

**Issue by rladygks329** [wanted-pre-onboarding-internship-1team/pre-onboarding-9th-2-1#34]
발전 시키고 싶은게 있으면 적어주세요

## Todo
- [x] 불필요한 코드 수정 및 temp 파일 제거
- [x]  husky 파일 오류 수정
- [x] UI 수정 및 Toast 추가
